version: '2'
services:

  dev:
    build:
      context: ${BIOPLATFORMS_CONTEXT}
      dockerfile: Dockerfile
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:${GIT_BRANCH}-${BIOPLATFORMS_PATH_TAG}

  prod:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:${BIOPLATFORMS_PATH_TAG}

  prod-date:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:${BIOPLATFORMS_PATH_TAG}-${BIOPLATFORMS_BUILD_DATE}
